apiVersion: apps/v1
kind: Deployment
metadata:
  name: fs-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: fs-deployment
  template:
    metadata:
      labels:
        app: fs-deployment
    spec:
      containers:
        - name: my-container
          image: nginx:latest
          ports:
            - containerPort: 80
          volumeMounts:
            - name: my-volume
              mountPath: /data
      volumes:
        - name: my-volume
          persistentVolumeClaim:
            claimName: filestore-pvc